# Generated by Django 4.0.3 on 2022-03-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pescription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pescription',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='pescription_image',
            name='image',
            field=models.ImageField(null=True, upload_to='pesceiption/'),
        ),
    ]
