# Generated by Django 4.0.3 on 2022-03-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pescription', '0002_pescription_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pescription',
            name='image',
            field=models.ImageField(null=True, upload_to='pesceiption/'),
        ),
        migrations.DeleteModel(
            name='Pescription_image',
        ),
    ]
