# Generated by Django 4.0.3 on 2022-03-16 05:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_content', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('madicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Madicine', to='catalog.madicine')),
            ],
        ),
    ]
