# Generated by Django 4.0.3 on 2022-03-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_content',
            field=models.TextField(),
        ),
    ]
