# Generated by Django 4.0.3 on 2022-03-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='madicine',
            name='image',
            field=models.ImageField(null=True, upload_to='medicine/'),
        ),
    ]
