# Generated by Django 4.0.3 on 2022-03-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='oredered',
            new_name='ordered',
        ),
    ]
